# Generated by Django 5.0.6 on 2024-08-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shippingaddress_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
    ]
