# Generated by Django 5.0.6 on 2024-08-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_id_alter_order_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='id',
        ),
    ]
